name: Auto Respond to Issues with Gemini

on:
  issues:
    types: [opened]

jobs:
  auto-respond:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install google-generativeai

      - name: Generate Response with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          import google.generativeai as genai
          import os

          genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
          model = genai.GenerativeModel("gemini-pro")

          issue_title = os.getenv("ISSUE_TITLE", "No Title")
          issue_body = os.getenv("ISSUE_BODY", "No Description")

          prompt = f"Respond to this GitHub issue in a helpful way:\n\nTitle: {issue_title}\nDescription: {issue_body}"
          response = model.generate_content(prompt)

          with open("issue_response.txt", "w") as f:
              f.write(response.text)

          print("Generated Response:", response.text)

      - name: Comment on Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('issue_response.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: response
            });
